# -*- coding: utf-8 -*-
"""위스퍼엑스 모델 - 프로모션 모델

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lM6Xq6MoYoHh7WXib8wRqFhyFszo6Cga
"""

import numpy as np
import torch
import faster_whisper
import whisperx
from importlib.metadata import version

print("numpy:", np.__version__)
print("torch:", torch.__version__)
print("faster_whisper:", faster_whisper.__version__)
print("whisperx:", version("whisperx"))
print("cuda:", torch.cuda.is_available())

# ================================
# 1+2 통합 셀: 환경 + 모델 로드 (최종)
# ================================

# 🔹 설치 (최신 호환 조합)
!pip uninstall -y whisperx faster-whisper ctranslate2 av -q

!pip install --no-cache-dir "faster-whisper==1.2.1" -q
!pip install --no-cache-dir "whisperx==3.8.4" -q

# ================================
# 🔹 numpy 호환 패치 (중요)
# ================================
import numpy as np
if not hasattr(np, "NaN"):
    np.NaN = np.nan

# ================================
# 🔹 import
# ================================
import torch
import whisperx
import pandas as pd
import subprocess
import time
from google.colab import files
from importlib.metadata import version

# ================================
# 🔹 환경 확인
# ================================
print("numpy:", np.__version__)
print("torch:", torch.__version__)
print("faster_whisper:", __import__("faster_whisper").__version__)
print("whisperx:", version("whisperx"))
print("cuda:", torch.cuda.is_available())

# ================================
# 🔹 디바이스 설정
# ================================
device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

# ================================
# 🔹 WhisperX 모델 로드
# ================================
print("\n[1] WhisperX 모델 로드 중...")
model = whisperx.load_model(
    "large-v3",
    device=device,
    compute_type="float16" if device == "cuda" else "int8",
    language="ko"
)

# ================================
# 🔹 Align 모델 로드
# ================================
print("[2] Align 모델 로드 중...")
model_a, metadata = whisperx.load_align_model(
    language_code="ko",
    device=device
)

print("\n✅ WhisperX + Align 모델 로드 완료")

from google.colab import files
uploaded = files.upload()
AUDIO_PATHS = list(uploaded.keys())
print("업로드된 파일:", AUDIO_PATHS)

import torch
import whisperx
from pyannote.audio import Pipeline
import subprocess
import pandas as pd
from google.colab import files
import time

import os
HF_TOKEN = os.environ.get("HF_TOKEN", "")  # ← 환경변수 또는 Colab Secrets 사용. 절대 코드에 직접 적지 마세요.
device = "cuda"

model = whisperx.load_model("large-v3", device=device, compute_type="float16", language="ko")
model_a, metadata = whisperx.load_align_model(language_code="ko", device=device)

diarize_model = Pipeline.from_pretrained(
    "pyannote/speaker-diarization-3.1",
    token=HF_TOKEN
).to(torch.device(device))

def convert_audio(input_path):
    output_path = input_path.rsplit(".", 1)[0] + "_converted.wav"
    subprocess.run([
        "ffmpeg", "-y", "-i", input_path,
        "-ar", "16000", "-ac", "1", "-f", "wav", output_path
    ], capture_output=True)
    return output_path

def diarize_to_df(diarize_output):
    annotation = diarize_output.speaker_diarization
    rows = []
    for turn, _, speaker in annotation.itertracks(yield_label=True):
        rows.append({"start": turn.start, "end": turn.end, "speaker": speaker})
    return pd.DataFrame(rows)

def process_audio(AUDIO_PATH):
    print("\n" + "="*60)
    print("파일:", AUDIO_PATH)
    print("="*60)

    converted = convert_audio(AUDIO_PATH)
    result = model.transcribe(converted, language="ko")
    result = whisperx.align(result["segments"], model_a, metadata, converted, device)
    diarize_output = diarize_model(converted)
    diarize_df = diarize_to_df(diarize_output)
    print("화자 분리 행 수:", len(diarize_df))
    result = whisperx.assign_word_speakers(diarize_df, result)

    txt_path = AUDIO_PATH.rsplit(".", 1)[0] + ".txt"
    lines = []
    for seg in result["segments"]:
        speaker = seg.get("speaker", "UNKNOWN")
        start = round(seg["start"], 1)
        end = round(seg["end"], 1)
        line = f"[{speaker}] {start}s ~ {end}s : {seg['text']}"
        print(line)
        lines.append(line)

    with open(txt_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return txt_path

# 5개씩 배치 처리, 배치 끝날 때 일괄 다운로드
BATCH_SIZE = 5
total = len(AUDIO_PATHS)

for batch_start in range(0, total, BATCH_SIZE):
    batch = AUDIO_PATHS[batch_start:batch_start + BATCH_SIZE]
    batch_num = batch_start // BATCH_SIZE + 1
    total_batches = (total - 1) // BATCH_SIZE + 1

    print(f"\n{'#'*60}")
    print(f"배치 {batch_num} / {total_batches}  ({batch_start+1}~{min(batch_start+BATCH_SIZE, total)} / 전체 {total}개)")
    print(f"{'#'*60}")

    txt_paths = []
    for AUDIO_PATH in batch:
        txt_path = process_audio(AUDIO_PATH)
        txt_paths.append(txt_path)

    # 배치 완료 후 일괄 다운로드
    print(f"\n배치 {batch_num} 완료 → 다운로드 시작 ({len(txt_paths)}개)")
    for txt_path in txt_paths:
        print(f"  다운로드: {txt_path}")
        files.download(txt_path)
        time.sleep(1)  # 다운로드 간 간격

    print(f"배치 {batch_num} 다운로드 완료")
    time.sleep(3)

print("\n전체 처리 완료!")

